---
- hosts: kvm_host
  tasks:
    - name: Prepare Libvirt
      block:
        - name: Setup prereqs
          import_role:
            name: prepare_libvirt
            tasks_from: setup_prereqs.yaml
        - name: Configure libvirt and dependencies for Openshift
          import_role:
            name: prepare_libvirt
            tasks_from: configure.yaml
      become: yes
      when: state is not defined or state == 'present'

- hosts: bootstrap:control
  gather_facts: no
  tasks:
    - name: Create VMs
      include_role: 
        name: boot_vm
        apply:
          delegate_to: "{{ groups['kvm_host'] | first }}"
      vars:
        ansible_become: yes
      when: state is not defined or state == 'present'
