---
- name: check if VM already exists
  virt:
    command: list_vms
  register: all_vms

# TODO: Make idempotent
- name: Destroy old VM
  shell: |
    virsh destroy {{ inventory_hostname }}
    virsh undefine --remove-all-storage {{ inventory_hostname }}
  when: "inventory_hostname in all_vms.list_vms"

# want fix: move to using the virt module...
- name: install VM
  shell: >-
    virt-install
    --name {{ inventory_hostname }}
    --hvm
    --virt-type kvm
    --pxe
    --arch x86_64
    --os-type linux
    --os-variant rhel8.0
    --network network=openshift,mac="{{ spec.mac }}"
    --vcpus {{ spec.cpu }}
    --ram {{ spec.ram }}
    --disk pool=default,size={{ spec.disk }},format=qcow2,cache={{ spec.disk_cache }}
    --check disk_size=off
    --nographics
    --noautoconsole
    --boot menu=on,useserial=on
  register: result
  retries: 3
  delay: 3
  until: result is not failed

- name: Waiting for end of the initial installation
  virt:
    name: "{{ inventory_hostname }}"
    command: status
  register: result
  until: result.status == "shutdown"
  retries: 100
  delay: 10

- name: Restart VM
  virt:
    name: "{{ inventory_hostname }}"
    state: running

- name: Waiting for sshd
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 10
    search_regex: OpenSSH
    state: started
    timeout: 1200
